[workspace]
members = [
	"common",
	"plugin-manager",
	"requirements",
]
exclude = ["plugins"]

[profile.dev]
opt-level = 3

[workspace.dependencies]
serde = { version = "1.0.144", features = ["derive"], default-features = false}
serde_cbor = { version = "0.11" }
