[workspace]
members = [
	"common",
	"providers",
	"requirements",
	"engine",
]

[profile.dev]
opt-level = 3

[workspace.dependencies]
serde = { version = "1.0.144", features = ["derive"] }
async-trait = { version = "0.1.57", default-features = false }
ethereum-types = { version = "0.14.1" }
thiserror = { version = "1.0.24", default-features = false }
