[workspace]
members = [
	"common",
	"providers",
	"requirements",
	"engine",
]

[profile.dev]
opt-level = 3

[workspace.dependencies]
serde = { version = "1.0.144", features = ["derive"] }
reqwest = { version = "0.11.11", features = ["json"] }
async-trait = { version = "0.1.57", default-features = false }
ethereum-types = { version = "0.14.1" }
shiba = { version = "0.1.1", default-features = false }
thiserror = { version = "1.0.24", default-features = false }
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
