[package]
name = "rusty-gate-requirements"
description = "Requirement types for the Guild-Network"
version = "0.1.0"
repository = "https://github.com/agoraxyz/requirement-engine-v2"
readme = "README.md"
license = "MIT"
authors = ["Shronk <ureshpohar@gmail.com>"]
keywords = ["guild", "guild-network", "requirements"]
categories = [
    "cryptography", "cryptography::cryptocurrencies", "data-structures"
]
edition = "2021"

[features]
nomock = []

[dev-dependencies]
shiba = { version = "0.1.1", default-features = false }
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }

[dependencies]
serde = { workspace = true }
reqwest = { workspace = true }
async-trait = { workspace = true }
ethereum-types = { workspace = true }
rusty-gate-common = { path = "../common" }
rusty-gate-providers = { path = "../providers" }
