name: general code check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  fmt:
    name: formatting
    runs-on: rust
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
  test:
    runs-on: rust

    env:
      RUSTFLAGS: -Dwarnings # fails on warnings as well

    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
          profile: minimal

      - uses: actions-rs/clippy@master
        with:
          args: --all-features --all-targets

      - uses: actions/checkout@v2

      - name: build
        run: cargo build --color=always --all-targets

      - name: clippy
        run: cargo clippy --color=always --all-targets --examples --tests

      - name: test
        run: |
          cargo t
          cat > ../providers.json << EOF
          {
            "ETHEREUM_RPC": {
              "rpc_url": "${{ secrets.ETHEREUM_RPC }}"
            },
            "POLYGON_RPC": {
              "rpc_url": "${{ secrets.POLYGON_RPC }}"
            },
            "BSC_RPC": {
              "rpc_url": "${{ secrets.BSC_RPC }}"
            },
            "GNOSIS_RPC": {
              "rpc_url": "${{ secrets.GNOSIS_RPC }}"
            },
            "ARBITRUM_RPC": {
              "rpc_url": "${{ secrets.ARBITRUM_RPC }}"
            },
            "GOERLI_RPC": {
              "rpc_url": "${{ secrets.GOERLI_RPC }}"
            },
          }
          EOF
          cargo t --features nomock
