name: general code check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  fmt:
    name: formatting
    runs-on: rust
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
  test:
    runs-on: rust

    env:
      RUSTFLAGS: -Dwarnings # fails on warnings as well
      ETHEREUM_RPC: ${{ secrets.ETHEREUM_RPC }}
      POLYGON_RPC: ${{ secrets.POLYGON_RPC }}
      BSC_RPC: ${{ secrets.BSC_RPC }}
      GNOSIS_RPC: ${{ secrets.GNOSIS_RPC }}
      ARBITRUM_RPC: ${{ secrets.ARBITRUM_RPC }}
      GOERLI_RPC: ${{ secrets.GOERLI_RPC }}

    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
          profile: minimal

      - uses: actions-rs/clippy@master
        with:
          args: --all-features --all-targets

      - uses: actions/checkout@v2

      - name: build
        run: cargo build --color=always --all-targets

      - name: clippy
        run: cargo clippy --color=always --all-targets --examples --tests

      - name: plugins/evm_balance
        run: |
          cd plugins/evm_balance
          cargo fmt -- --check
          cargo b
          cargo clippy --color=always --all-targets --examples --tests
          cargo t --all-features
          cd ../..

      - name: plugins/sol_balance
        run: |
          cd plugins/sol_balance
          cargo fmt -- --check
          cargo b
          cargo clippy --color=always --all-targets --examples --tests
          cd ../..
          cargo t --all-features

      - name: config
        run: |
          cat > ./config.json << EOF
          {
            "evm_balance": "../plugins/evm_balance/target/debug/libevm_balance.so",
            "sol_balance": "../plugins/sol_balance/target/debug/libsol_balance.so",
            "ethereum": {
              "rpc_url": "${ETHEREUM_RPC}",
              "contract": "0x5ba1e12693dc8f9c48aad8770482f4739beed696",
              "balancy_id": 1
            },
            "bsc": {
              "rpc_url": "${BSC_RPC}",
              "contract": "0x41263cba59eb80dc200f3e2544eda4ed6a90e76c",
              "balancy_id": 56
            },
            "gnosis": {
              "rpc_url": "${GNOSIS_RPC}",
              "contract": "0xb5b692a88bdfc81ca69dcb1d924f59f0413a602a",
              "balancy_id": 100
            },
            "polygon": {
              "rpc_url": "${POLYGON_RPC}",
              "contract": "0x11ce4B23bD875D7F5C6a31084f55fDe1e9A87507",
              "balancy_id": 137
            },
            "arbitrum": {
              "rpc_url": "${ARBITRUM_RPC}",
              "contract": "0x52bfe8fE06c8197a8e3dCcE57cE012e13a7315EB"
            },
            "goerli": {
              "rpc_url": "${GOERLI_RPC}",
              "contract": "0x77dCa2C955b15e9dE4dbBCf1246B4B85b651e50e"
            },
            "solana_main": "https://api.mainnet-beta.solana.com"
          }
          EOF

      - name: test
        run: |
          export CONFIG_PATH=../config.json
          cargo t --all-features
